### PR TITLE
Update the crate to compile again with later Rust and `librpm` versions

### PR DESCRIPTION
**Pull request by ErichDonGubler**
See commits for more details -- if you'd like me to handle some other work doing updates, then just let me know!

### CODE REVIEW

**Comment by tarcieri** [comment]
Hi @ErichDonGubler, thanks for identifying the root cause of #6 and indeed you have pinpointed the core problem. I'm also quite glad you're interested in helping!

At first glance this PR looks good, however it seems our CI is broken, so I will need to investigate fixing it.

I'm also curious if you know offhand how this affects compatibility. I can investigate on my own, but I'm curious if this will still build against librpm as included in e.g. CentOS 7 (I know 8 is coming soon, but)

**Comment by ErichDonGubler** [comment]
Looking at [the CentOS 7 package index](http://mirror.centos.org/centos/7/os/x86_64/Packages/) and searching for `rpm-devel`, looks like `librpm` 4.11 is still in use there -- you're either going to need to maintain separate versions of this crate for different `librpm` versions (i.e. `0..1.x` for pre-4.12 and `0.2.x` for 4.12 until the next breaking API changes) or just drop support for all but latest. The strategy you pick will most likely depend on your commitment to backwards compatibility and how much free time you have. :stuck_out_tongue: 

Looks like CentOS 8 will be using at least `librpm` 4.14, according to [this build](https://koji.mbox.centos.org/koji/buildinfo?buildID=92) I found with some Google-fu.

**Comment by tarcieri** [comment]
@ErichDonGubler ok, let's go ahead and update it, and I will continue using the old version on CentOS 7 and update when I get on CentOS 8

**Comment by tarcieri** [comment]
@ErichDonGubler is there a particular distro/release you'd like to test against (perhaps Fedora?) I can get CI working again with that.

**Comment by ErichDonGubler** [comment]
Fedora is what I use right now, but I'm also open to Arch, Ubuntu...I'm not generally intimidated by most distros. :)

**Comment by tarcieri** [comment]
@ErichDonGubler I've set up Travis CI (which uses Ubuntu) and gone ahead and done a 2018 edition upgrade.

The tests are hanging though, so I disabled them in .travis.yml. Need to investigate why.

Let me know if that works. Otherwise I can investigate Fedora/CircleCI or something. Travis is nice in that I don't have to maintain a Docker image.

**Comment by tarcieri** [comment]
I believe this was obsoleted by #14

**Pull request closed without merging**
